### PR TITLE
Improve design and update pakages

### PR DESCRIPTION
**Pull request by arnxv0**
Improved the overall style to a bit darker theme and changed font sizes to make it more readable.

### CODE REVIEW

**Comment by trybick** [comment]
@arnxv0 Thank you for updating the dependencies. I changed the target branch to master actually (my bad for outdated documentation in readme). Would you mind resolving the merge conflict? 

If you would like to do another PR, you're welcome to do one for updating the Contributing section of the readme to specify the master branch.

**Comment by arnxv0** [comment]
@trybick I'll work on it, I noticed a few changes in the main branch. I'll do the styling again and create a PR soon :)

Did you like the colors tho?

**Comment by trybick** [comment]
@arnxv0 Awesome, sounds good. I couldn't preview the colors because the netlify deploy preview only runs on master branch. Next time there should be a preview though!

**Comment by arnxv0** [comment]
@trybick I have created a new PR, check it out :)

**Comment by trybick** [comment]
Closing because I think PR #40 took care of it

**Pull request closed without merging**
